### ISSUE TITLE
please don't accept any new map

### ISSUE THREAD

**Issue by braainsiogame** [Quezler/mindustry__nydus--map-pool#24]
![image](https://user-images.githubusercontent.com/59963353/83351202-21f94080-a36c-11ea-92dc-50170d496f4e.png)

**Comment by braainsiogame** [comment]
please don't accept any new map

**Comment by braainsiogame** [comment]
please don't accept any new map

**Comment by BlueWolfGaming** [comment]
This issue has no logical reason to exist, I suspect it will be closed shortly.

**Comment by braainsiogame** [comment]
69 is a nice number

**Comment by braainsiogame** [comment]
please don't accept any new map

**Comment by BlueWolfGaming** [comment]
*Still not a logical reason.*

**Comment by braainsiogame** [comment]
it is logical you dumb guy

**Comment by BlueWolfGaming** [comment]
It is not, the addition of new maps into the server is vastly more important, for the diversity and the pissing off noobs.

**Comment by ritzip** [comment]
uncultured swine right there

**Comment by modern500** [comment]
I agree,  new  maps should  be accepted.  A stupid number  should not  halt the growth of nydus's maps. Braainsiogame is the uncultured  one here.  I just  made my best map, and it needs  to  be accepted.  Stop freaking out about  a stupid  number!

**Comment by braainsiogame** [comment]
i'll leave this on

**Comment by Quezler** [comment]
tchaikovsky no
